### ISSUE TITLE
请问为什么合并的文件是空的ts文件？

### ISSUE THREAD

**Issue by qfzack** [necan/iMoocMerger#1]

**Comment by necan** [comment]
请提交软件截图和你的目录结构。

**Comment by qfzack** [comment]
![image](https://user-images.githubusercontent.com/22722784/76070888-45605980-5fd0-11ea-927a-e8942486a5af.png)
![image](https://user-images.githubusercontent.com/22722784/76070927-527d4880-5fd0-11ea-871d-a9a5f21fd038.png)
合并界面闪退，因该是出了问题
![image](https://user-images.githubusercontent.com/22722784/76070989-7476cb00-5fd0-11ea-8ba5-710628b4ee8a.png)

**Comment by necan** [comment]
打开cmd，进入到merger.exe文件夹，然后输入merger.exe，再把出错的界面截图提交给我看看。

**Comment by qfzack** [comment]
> 打开cmd，进入到merger.exe文件夹，然后输入merger.exe，再把出错的界面截图提交给我看看。

**Comment by qfzack** [comment]
![image](https://user-images.githubusercontent.com/22722784/76072285-a7ba5980-5fd2-11ea-9982-54bc6543a19e.png)
zhi'qian之前路径有中文，改了之后现在还在等

**Comment by necan** [comment]
支持中文路径的，还有最好能提交出错的信息。

**Comment by qfzack** [comment]
![image](https://user-images.githubusercontent.com/22722784/76073190-324f8880-5fd4-11ea-9a91-8e9f213bb0b4.png)

这是出错的信息

**Comment by necan** [comment]
你下载的视频文件缺少密钥文件 `key.hxk`，没有密钥视频无法解密。你的视频是用 app 下载的吗？

**Comment by qfzack** [comment]
是的，手机的慕课网

**Comment by necan** [comment]
是安卓 app？

**Comment by qfzack** [comment]
对的

**Comment by necan** [comment]
慕课网app是什么版本？

**Comment by qfzack** [comment]
7.3.1

**Comment by necan** [comment]
可能是app没有下载那个视频的 `key.hxk` ，你重新下载那个没有 `key.hxk` 的视频，确保下载到 `key.hxk`再拷贝到电脑上。

**Comment by qfzack** [comment]
好的，感谢您的解答
