### ISSUE TITLE
强啊，想知道是怎么做到的？

### ISSUE THREAD

**Issue by kaoke2016** [necan/iMoocMerger#2]
那个IV是0吗，按网上说的解码我这根本不成功，想知道是怎么回事？

`openssl aes-128-cbc -d -in 1a3088c2ca79ab55.ts -out 1a3088c2ca79ab55_0.ts -nosalt -K 7hFZmqqqu1SGjhlULVQqVJCWq1TgA1SlVA==xmGxM1aVZylGs0yDidd5pgGc  -iv 0`

**Comment by necan** [comment]
要破解 `key` 的加密算法，至于怎么破解，我就不公开了。

**Comment by kaoke2016** [comment]
好的，感谢解答

**Comment by MonsterGene** [comment]
大神，可以加个微信好友吗？1020887639
