### ISSUE TITLE
lj类型课程合并报错

### ISSUE THREAD

**Issue by gadfly3173** [necan/iMoocMerger#4]
![捕获](https://user-images.githubusercontent.com/28685179/79402844-a9a70d80-7fbf-11ea-923d-deb223135b0e.PNG)

**Comment by necan** [comment]
你是指文件夹是 `lj_` 开头的？

**Comment by gadfly3173** [comment]
> 你是指文件夹是 `lj_` 开头的？

是的

**Comment by necan** [comment]
我没有这个类型的课程，能提供一份来给我看看吗？

**Comment by gadfly3173** [comment]
https://1drv.ms/u/s!Aqqr4BIdbCmVj0a2PDkTXHJ_iCTu?e=MSNB91

> 我没有这个类型的课程，能提供一份来给我看看吗？

**Comment by necan** [comment]
已更新，注册目录结构已更改，注意查看说明。
